name: backend-deploy
on:
    push:
        branches:
            main
jobs:
    Deploy:
        runs-on: backend
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Deploy
              run: |
                cd Blog/Backend
                npm install --legacy-peer-deps
                sudo systemctl restart backendService.service
