name: backend-deploy
on:
    workflow_dispatch:
    push:
        branches:
            main
jobs:
    Deploy:
        runs-on: backend
        steps:
            # - name: Checkout
            #   uses: actions/checkout@v2
            - name: Deploy
              run: |
                cd /home/ec2-user/Blog/Backend
                git pull
                npm install --legacy-peer-deps
                sudo systemctl restart backendService.service
