name: EC2 Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, linux]

    steps:
    - name: Install dependencies
      run: |
        sudo yum install -y git
        sudo yum install -y nodejs
        sudo yum install -y nginx
        sudo mkdir -p /var/www/html
    - name: Cloning
      run: git clone https://github.com/Hari-1202/Blog.git
    - name: Redirect
      run: |
        cd Blog/src
        npm install
        npm run build
        npm start